### PR TITLE
Plot update

### LINKED ISSUE #102: Disentangle plot routines from the `diag` class
The `heatmap_comparison_pi` and `heatmap_comparison_gm` have docstrings to improve and they should get rid of the `diag` requirement, since the class is only needed for model and exp vars and they can be passed to the function so that it is possible to use them also without rerunning the entire diagnostic.

### PR DESCRIPTION
**Pull request by mnurisso**
Close #102 

`diag` is not anymore a plot argument, but a dictionary with the relevant `diag` elements is taken, so that the function can be used individually to modify a plot independently from the diagnostic.

I'm planning to add a `title` kwarg and the possibility to give a dict and not only a pandas dataframe so that we can use more easily the function outside of the entry point.

### CODE REVIEW

**Comment by oloapinivad** [comment]
Since tests are passed I assume this could be merged, do you tried this on your local machine could you confirm?

**Comment by mnurisso** [comment]
Yes, I tried it but I'd like to add a couple features more if you're ok with it, namely:

- title kwarg if a custom one is needed
- possibility to use a dict and not only a pandas dataframe to plot

Let me know if you want them in a new PR, if yes I'm ok with merging this one

**Comment by oloapinivad** [comment]
There is no rush, so please continue working on this PR! Thanks a lot!

**Comment by oloapinivad** [comment]
Closing since it is integrated in #110

**Pull request closed without merging**
