### PR TITLE
CMOR compliance

### PR DESCRIPTION
**Pull request by jhardenberg**
This branch implements the ability to work with CMOR files. The idea is to have a new dedicated interface file. One of the main issues to be solved is the ability to work with multiple separate file variable per variable.
Solves #25

### CODE REVIEW

**Comment by jhardenberg** [comment]
The current version seems to be working well and is probably close to merge.
A small required change was in `config.yml` where now we have an explicit `interface` entry which selects the appropriate interface file. This is distinguished from "model" since that is the actual model name and many models can share the same interface (as for cmip output).  Some new options have been added to the command line,, like the "ensembles" option in order to allow to select among CMIP ensembles, versions etc. Some additional ones may have to be added. 
A major change had to be included in c5b954622f126f4b6f886e06dad56ffc8e160c2c in order to allow merging in input separate files for derived variables. 
A further change implemented is in the masks (land and sea). These are now 1 and 0 masks (no missing values) since often in cdo multiplying by a missing value fails. The masked_meansum now uses these directly just multiplying, while cdopipe.mask now uses more correctly the cdo operator `ifthen`.

Examples for usage (e.g. on mafalda)
`./global_mean historical 1990 1999 -j 8`
(it works because I have EC-Earth3 as model in my config.yml, I could also specify the option "-m EC-Earth3"

What is missing:

- [ ] Currently only an interface for CMIP6 is provided, try and write also a CMIP5 one (I would merge before having done this though)
- [ ] CMIP output can group years 'at random' (e.g 1990-1999, 2000-2009 etc). In these cases the current code would not find the correct year
- [ ] What happens if more than one file match the search (e.g. multiple versions, multiple ensemble members)? To be checked.

**Comment by jhardenberg** [comment]
Ok, the latest commit implements CMIP5 compatibility (try with with IPSL-CM5A-LR on mafalda):
`./performance_indices.py historical 1990 1999 -e r1i1p1 -j 12 -m IPSL-CM5A-LR`
we need to specify the ensemble since the default is r1i1p1f1 ....

**Comment by jhardenberg** [comment]
Ok, all looks good. Time for a review ;)

**Comment by jhardenberg** [comment]
To summarize, it can be tried on mafalda (where I have the necessary data in synda) with a config.yml like this one:
```
# Choice of interface
interface: CMIP6
# Choice of model name. It is printed in the output table
model:
   #name: IPSL-CM5A-LR
   name: EC-Earth3

dirs:
   exp: /work/datasets/synda/data
   tab: /home/jost/work/ece4/tab
   clm: /home/jost/work/ece4/ECmean4/climatology
```
at the moment choose IPSL-CM5A-LR to test CMIP5. So, assuming the right interface (CMIP5 or CMIP6) has been set in config (indeed an additional command line option to select the interface could be useful for this), we can run:
`./global_mean.py historical 1990 1999 -j 12 -m EC-Earth3 `
or
`./global_mean.py historical 1990 1999 -j 12 -m IPSL-CM5A-LR -e r1i1p1`

**Comment by oloapinivad** [comment]
I tried today to run it on Wilma. I see a minor weakness that is unfortunately a bit annoying, i.e. it assumes the directory structure as on the ESGF. this means that any other choiche, as the one I have on the archive, is completely incompatible. It would be better to have something as a `find` call to look for the required files within a defined folder. It would be slower, but it will find only the required files wherever they are (CMIP6 files are self-descriptive, so the path structure is irrelevant but for the version). I could see tomorrow if I can implement this...

**Comment by oloapinivad** [comment]
Uhm, after checking the method used so far I see that it would be an extra level of complexity, really not necessary. It is easier to tweak the interface files in a way that is compatibile with the archive used on the local machine. It work quite smoothly.

**Review by oloapinivad — APPROVED** [review]

**Pull request merged**
