### PR TITLE
Update climatology

### PR DESCRIPTION
**Pull request by oloapinivad**
This pull request handle a the introduction of a different reference dataset, which updates the original RK08 found in the older ECmean. However, to keep backward compatibility, is still possible to compare to the default climatology (now named RK08) but also to the updated one (named EC22). The default climatology is still RK08, but this can be changed with the `-c` flag from command line. The new EC22 climatology comes with the possibility of using also a 1-degree resolution (r360x181), and it is computed on the 1990-2019 window and saved with NetCDF4 files.  It has been created on wilma `/home/paolo/scratch/ecmean_datasets` with the `create_all.sh` script. 

Overall, this required a minor readjustment of the code and the folder structure.  

Open issues: 

- [x] The new climatology is based on ORAS5, ERA5 (on 19 levels), CRU and MSWEP. ORAS5 is used for salinity, the new SST/SIC from ESA-CCI has been included too.
- [x] Net surface fluxes was missing: a comparison with NOCS dataset has been included.
- [x] Snow cover is included from ERA5, but is not present in files, so cannot be tested
- [x] The climatology creation script is a bash script which is now included in the repo for reproducibility. Of course it depends on local data which are not attached. 
- [x] There is an issue with regions that have very small variance in some datasets. Sometimes we get to absurd RMSE/VAR values which makes the RMSE to explode. This has been solved initially applying a threshold in minimum variance to be at least larger than a factor (variable-dependent and so a bit clumsy) than the maximum variance of a field when generating the new climatology. In the most recent commit, this has been replaced with a 5-sigma threshold (variable independent) on the log10 distribution of the variance. It removes the outliers and provide a robust climatology field. It is documented in the generation code.
- [x] Introduce the r360x180 and r180x90 climatologies which avoid grid point the the poles (which are unrealistic). the first and the last grid points have bounds at 90 degrees. Please keep in mind that the original RK08 uses a r180x91.
- [x] Interpolation is carried out before the variance computation: this provides more consistency in the estimation of the variance

### CODE REVIEW

**Comment by jhardenberg** [comment]
As discussed I suggest a 360x180 and a 180x90 climatology (so that the first gp boundary is at +90 centered at 89 for the 2° case). For surface fluxes we can use CERES-EBAF.

**Comment by oloapinivad** [comment]
Cant use CERES, there is no latent and sensible heat flux, using ICOADS up 2015 temporarily

**Comment by oloapinivad** [comment]
The script has been included in the repo `climatology_create_all.sh`

**Comment by oloapinivad** [comment]
further updates in the climatologies file, the branch is almost ready. still missing snow fraction, but we do not have it in data. also need to find some final choice for the variance issue.

**Comment by oloapinivad** [comment]
So everything seems in place:

A brief recap: all the variables cover the time frame 1990-2019, with a few exeptions
- CRU for t2m (up 2018, it will be fixed)
- MSWEP for precipitation
- ORAS5 for sea surface salinity and wind stresses
- ESA-CCI for SST and SIC
- NOCS for surface net flux over the ocean (up 2015, no more data available)
- ERA5 for SLP, zonal and meridional wind, specific humidity, temperature and snow cover

The datasets have been created on wilma with `climatology_create_all.sh`. r180x90 and r360x180 grids are so far available, I opted to avoid the original grid so far.
 
The climatology is still the default RK08 on the r180x91 grid, which means that the resolution for RK08 is hard-coded. 
To call the EC22 climatology is enough to do `./performance_indices.py EXP YEAR1 YEAR2 -c EC22`

Possible future extensions include:
- Flexible years selection (implies having all the yearly average on the archive to compute variance and mean on the go)
- Computation on original climatology grids

**Comment by jhardenberg** [comment]
@oloapinivad [include slp](https://github.com/oloapinivad/ECmean4/pull/27/commits/01ebdbdf1c0699987d6c135b6bc0079dfe38e4b3) changed make_atm_masks and make_atm_remap_weights from remapcon2 (and remapcon respectively) to remapbil. This actually changed slightly the results of the performance index calculation (really minor stuff) so that now pytest fails .... If you can confirm that this change from remapcon to remapbil is what we want we could simply update the reference PI results in the test directory

**Comment by oloapinivad** [comment]
> @oloapinivad [include slp](https://github.com/oloapinivad/ECmean4/pull/27/commits/01ebdbdf1c0699987d6c135b6bc0079dfe38e4b3) changed make_atm_masks and make_atm_remap_weights from remapcon2 (and remapcon respectively) to remapbil. This actually changed slightly the results of the performance index calculation (really minor stuff) so that now pytest fails .... If you can confirm that this change from remapcon to remapbil is what we want we could simply update the reference PI results in the test directory

So if I remember correctly the problem is that remapcon behaves in a very strange way when working with land-sea masks. An example here attached is the remapping in bilinear (left) and conservative (right) of CRU dataset from the original 0.25 grid to r180x91. Both results are not satisfactory, but remapcon is definitely not acceptable. We might need to apply masks in a more robust way, but for the momenti I would use remapbil which guarantee a more standard and decent results. 

Schermata 2022-05-30 alle 09 10 06

**Comment by jhardenberg** [comment]
Yep, I have seen that. I am testing myself on mafalda

**Comment by jhardenberg** [comment]
Lol: the difefrence is in 
```
diff PI4_RK08_cpld_EC-Earth4_r1i1p1f1_1990_1990.txt PI4_RK08_cpld_1990_1990.ref
15c15
< | siconc  |   100.244   | ocean    | GISS      |    0.34 |       294.836    |
---
> | siconc  |   100.244   | ocean    | GISS      |    0.34 |       294.837    |
```
So rounding issues on some machines may lead to slightly different results?

**Comment by jhardenberg** [comment]
This is probably slightly different cdo versions on the machines?

**Comment by jhardenberg** [comment]
I would leave it as it is now so that it works on github. We need it to detect significant changes anyway, the fact that it gives a slightly different result on Atos is not very important. Unless we want to do the test reading in the two PI tables and checking if the differences are smaller than some small epsilon ....

**Comment by oloapinivad** [comment]
We might simply round at the second decimal point...


Il giorno lun 30 mag 2022 alle ore 11:26 Jost von Hardenberg <
***@***.***> ha scritto:

**Comment by jhardenberg** [comment]
Let me check if it is possible to round those numbers ....

**Comment by jhardenberg** [comment]
Ok, I added also a "-r" option to override resolution from command line (if not specified config.yml wins). Example: `-r r360x180 -k EC22`   Of course for RK08 resolution is fixed to r180x91.

**Comment by jhardenberg** [comment]
If this test passes I would merge !

**Comment by oloapinivad** [comment]
Test are passing on Atos too, I am merging this into the main.

**Pull request merged**
